afpa_addition_calcul:
    pattern:  /{a}/{b}
    defaults: { _controller: AfpaAdditionBundle:Default:calcul }
    requirements:
        a: \d*
        b: \d*

afpa_addition_result:
    pattern:  /result/{result}
    defaults: { _controller: AfpaAdditionBundle:Default:result }